// <auto-generated />
namespace Planing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pl315 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pl315));
        
        string IMigrationMetadata.Id
        {
            get { return "201602151050056_pl315"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
